const data={
    products:
    [
        {   id:'1',
            name:'Deal1',
            price:500,
        },
        {   id:'2',
            name:'Deal2',
            price:1000,
            
        },
        {   id:'3',
           name:'Deal3',
            price:1500,
            
            
        },
        {   id:'4',
            name:'Pepperoni Pizza',
            size1:'Small Rs.350',
            size2:'Medium Rs.650',
            size3:'Large Rs.950',
        },
        {   id:'5',
            name:'Cheese Pizza',
            size1:'Small Rs.350',
            size2:'Medium Rs.650',
            size3:'Large Rs.950',
        },
        {   id:'6',
            name:'Buffalo Pizza',
            size1:'Small Rs.350',
            size2:'Medium Rs.650',
            size3:'Large Rs.950',
        },
        {   id:'7',
            name:'Meat Pizza.',
            size1:'Small Rs.350',
            size2:'Medium Rs.650',
            size3:'Large Rs.950',
        },
        {   id:'8',
            name:'Supreme Pizza.',
            size1:'Small Rs.350',
            size2:'Medium Rs.650',
            size3:'Large Rs.950',
        },
        {   id:'9',
            name:'Hawaiian Pizza',
            size1:'Small Rs.350',
            size2:'Medium Rs.650',
            size3:'Large Rs.950',
       },
        {   id:'10',
            name:'Garlic Bread',
            size1:'Small Rs.350',
            size2:'Medium Rs.650',
            size3:'Large Rs.950',
        },
        {   id:'11',
            name:'Potato wedges',
            size1:'4 pieces Rs.250',
            size2:'6 pieces Rs.375',
            size3:'8 pieces Rs.500',
        },
        {   id:'12',
            name:'Chicken Wings',
            size1:'4 pieces Rs.250',
            size2:'6 pieces Rs.375',
            size3:'8 pieces Rs.500',
        },

    ],

};
